=== nebojsabasaric94/XML_projekat/National_bank_xml/src/main/resources/strukturaRtgsNaloga.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://strukturaRtgsNaloga.com" xmlns:srtgs="http://strukturaRtgsNaloga.com">
    <xs:complexType name="struktura_rtgs_naloga">
        <xs:sequence>
            <xs:element name="id_poruke">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:maxLength value="50"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="swift_kod_banke_duznika">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:length value="8"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="obracunski_racun_banke_duznika">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="\d{3}-\d{13}-\d{2}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="swift_kod_banke_poverioca">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:length value="8"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="obracunski_racun_banke_poverioca">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="\d{3}-\d{13}-\d{2}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="duznik_nalogodavac">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:maxLength value="255"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="svrha_placanja">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:maxLength value="255"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="primalac_poverilac">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:maxLength value="255"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="racun_duznika">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="\d{3}-\d{13}-\d{2}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="model_zaduzenja">
                <xs:simpleType>
                    <xs:restriction base="xs:int">
                        <xs:minInclusive value="10"/>
                        <xs:maxInclusive value="99"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="poziv_na_broj_zaduzenja">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:maxLength value="20"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="racun_poverioca">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="\d{3}-\d{13}-\d{2}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="model_odobrenja">
                <xs:simpleType>
                    <xs:restriction base="xs:int">
                        <xs:minInclusive value="10"/>
                        <xs:maxInclusive value="99"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="poziv_na_broj_odobrenja">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:maxLength value="20"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="iznos">
                <xs:simpleType>
                    <xs:restriction base="xs:decimal">
                        <xs:totalDigits value="15"/>
                        <xs:fractionDigits value="2"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="datum_naloga" type="xs:date"/>
        <xs:attribute name="datum_valute" type="xs:date"/>
        <xs:attribute name="sifra_valute">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:length value="3"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>
    <xs:element name="getStrukturaRtgsNalogaRequest">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="strukturaRtgsNaloga" type="srtgs:struktura_rtgs_naloga"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="getStrukturaRtgsNalogaResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="mt900" type="srtgs:mt900"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="mt900">
        <xs:sequence>
            <xs:element name="id_poruke">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:maxLength value="50"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="swift_banke_duznika">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:length value="8"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="obracunski_racun_banke_duznika">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="\d{3}-\d{13}-\d{2}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="id_poruke_naloga">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:maxLength value="50"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="iznos">
                <xs:simpleType>
                    <xs:restriction base="xs:decimal">
                        <xs:totalDigits value="15"/>
                        <xs:fractionDigits value="2"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="datum_valute" type="xs:date"/>
        <xs:attribute name="sifra_valute">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:length value="3"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>
    <xs:complexType name="mt910">
        <xs:sequence>
            <xs:element name="id_poruke">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:maxLength value="50"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="swift_kod_banke_poverioca">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:length value="8"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="obracunski_racun_banke_poverioca">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="\d{3}-\d{13}-\d{2}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="id_poruke_naloga">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:maxLength value="50"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="iznos">
                <xs:simpleType>
                    <xs:restriction base="xs:decimal">
                        <xs:totalDigits value="15"/>
                        <xs:fractionDigits value="2"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="datum_valute" type="xs:date"/>
        <xs:attribute name="sifra_valute">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:length value="3"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>
    <xs:element name="getMt910Request">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="mt910" type="srtgs:mt910"/>
                <xs:element name="rtgsNalog" type="srtgs:struktura_rtgs_naloga"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="getMt910Response">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="mt910" type="srtgs:mt910"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== nebojsabasaric94/XML_projekat/BankXml/src/main/resources/instance1.xml
<?xml version="1.0" encoding="UTF-8"?>
<getStrukturaRtgsNalogaRequest xmlns="http://strukturaRtgsNaloga.xml.com"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://strukturaRtgsNaloga.xml.com file:/C:/Users/Danilo/Desktop/XML/XML_projekat/BankXml/src/main/resources/strukturaRtgsNaloga.xsd">
    <strukturaRtgsNaloga>
        <id_poruke>id_poruke0</id_poruke>
        <swift_kod_banke_duznika>swift_ko</swift_kod_banke_duznika>
        <obracunski_racun_banke_duznika>000-0000000000000-00</obracunski_racun_banke_duznika>
        <swift_kod_banke_poverioca>swift_ko</swift_kod_banke_poverioca>
        <obracunski_racun_banke_poverioca>000-0000000000000-00</obracunski_racun_banke_poverioca>
        <duznik_nalogodavac>duznik_nalogodavac0</duznik_nalogodavac>
        <svrha_placanja>svrha_placanja0</svrha_placanja>
        <primalac_poverilac>primalac_poverilac0</primalac_poverilac>
        <racun_duznika>000-0000000000000-00</racun_duznika>
        <model_zaduzenja>54</model_zaduzenja>
        <poziv_na_broj_zaduzenja>poziv_na_broj_zaduze</poziv_na_broj_zaduzenja>
        <racun_poverioca>000-0000000000000-00</racun_poverioca>
        <model_odobrenja>54</model_odobrenja>
        <poziv_na_broj_odobrenja>poziv_na_broj_odobre</poziv_na_broj_odobrenja>
        <iznos>0.00</iznos>
    </strukturaRtgsNaloga>
</getStrukturaRtgsNalogaRequest>
